### ISSUE TITLE
Create function fails on windows with spaces in paths

### ISSUE THREAD

**Issue by jordanwalsh23** [twilio-labs/create-twilio-function#50]
OS: Windows 10 x64

Attempting to create the function in a directory that has a space throws an error.

```
C:\Users\Jordan Walsh\projects\launch-phone-redirect>npx create-twilio-function@next example
Error: EPERM: operation not permitted, mkdir 'C:\Users\Jordan'
TypeError: Cannot read property 'get' of undefined
    at errorMessage (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-message.js:38:39)
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:201:13)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:78:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:173:20)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97:27)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:496:27)
Install for create-twilio-function@next failed with code 7
```

The same code executed in a directory with no spaces works fine:

```
c:\projects>create-twilio-function launch-phone-redirect
√ Creating project directory
Please enter your Twilio credentials which you can find in your Twilio console (​https://twil.io/your-console​).
? Twilio Account SID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
? Twilio auth token [hidden]
√ Creating project directories and files
√ Downloading .gitignore file
√ Installing dependencies
╭──────────────────────────────────────────────────────────────────────────────╮
│                                                                              │
│   Success!                                                                   │
│                                                                              │
│   Created launch-phone-redirect at c:\projects                               │
│                                                                              │
│   Inside that directory, you can run the following command:                  │
│                                                                              │
│   npm start                                                                  │
│     Serves all functions in the ./functions subdirectory and assets in the   │
│     ./assets directory                                                       │
│                                                                              │
│   Get started by running:                                                    │
│                                                                              │
│   cd launch-phone-redirect                                                   │
│   npm start                                                                  │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

c:\projects>
```

**Comment by philnash** [comment]
Thank you for this report. I’ll take a look, but might need some help testing as I don’t have a Windows PC. I’m sure I can track it down though, thanks for the stack trace!

**Comment by philnash** [comment]
Hey @jordanwalsh23,

So this looks like it is an `npx` issue that remains unsolved: https://github.com/zkat/npx/issues/100.

There appears to be some workarounds, like [setting the npm cache name to use a specific pattern](https://github.com/zkat/npx/issues/146#issuecomment-384019497) or [symlinking the directory to one without spaces](https://github.com/zkat/npx/issues/100#issuecomment-484193572).

Anothe workaround would be to install this module globally and then using it, like this:

```bash
npm install -g create-twilio-function
create-twilio-function example
```

I'll close this as I can't fix the issue in this module, but let me know if those other bits work for you.

**Comment by jordanwalsh23** [comment]
All good @philnash - happy to proceed with the workarounds.  Using the directory with no spaces was good enough for me.  Just wanted to make sure it got logged.

**Comment by philnash** [comment]
Ok, cool! Glad it's not getting in your way and hopefully the `npx` project can sort this out eventually.
